# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IZOWSbE0vrgeSLCOw1TC9kFo7z3P79u
"""

# -*- coding: utf-8 -*-
import os
import re
import json
import pandas as pd
import torch
import plotly.express as px
import streamlit as st
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# ==========================================
# 1. KONFIGURASI HALAMAN & CUSTOM CSS
# ==========================================
st.markdown("""
<style>

/* =========================
   GOOGLE FONT
========================= */

@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');

html, body, [class*="css"]{
    font-family:'Plus Jakarta Sans',sans-serif;
}

/* =========================
   BACKGROUND
========================= */

.stApp{

background:
radial-gradient(circle at top left,#DDEEFF 0%,transparent 45%),
radial-gradient(circle at bottom right,#D6F4FF 0%,transparent 35%),
linear-gradient(
180deg,
#F8FBFF,
#EEF5FC,
#E8F3FF
);
}

/* =========================
   SEMUA TEXT
========================= */

.stMarkdown{
    color:#183B63 !important;
}

/* =========================
   HEADER
========================= */

.header-container{

background:linear-gradient(
135deg,
#0B3D91,
#1565C0,
#42A5F5);

padding:55px;

border-radius:28px;

overflow:hidden;

position:relative;

box-shadow:
0 20px 45px rgba(0,0,0,.15);

margin-bottom:35px;

}

.header-container::after{

content:"";

position:absolute;

right:-80px;

top:-80px;

width:220px;

height:220px;

border-radius:50%;

background:rgba(255,255,255,.15);

}

.header-title{

font-size:48px;

font-weight:800;

letter-spacing:.5px;

margin-bottom:12px;

}

.header-subtitle{

font-size:20px;

opacity:.95;

}

/* =========================
   SIDEBAR
========================= */

section[data-testid="stSidebar"]{

background:
linear-gradient(
180deg,
#003C8F,
#1565C0);

border-right:1px solid rgba(255,255,255,.2);

}

section[data-testid="stSidebar"] *{

    color:black !important;

}

/* =========================
   BUTTON
========================= */

.stButton>button{

height:55px;

border-radius:15px;

font-size:17px;

font-weight:700;

background:linear-gradient(
135deg,
#1565C0,
#42A5F5);

transition:.3s;

border:none;

color:white;

}

.stButton>button:hover{

transform:
translateY(-4px);

box-shadow:
0 15px 35px rgba(25,118,210,.35);

}

/* =========================
   DOWNLOAD BUTTON
========================= */

.stDownloadButton>button{

    background:#1976D2;

    color:white;

    border:none;

    border-radius:12px;

}

.stDownloadButton>button:hover{

    background:#1565C0;

}

/* =========================
   TEXT AREA
========================= */

textarea,
textarea:focus,
textarea:active {

    background: #FFFFFF !important;
    color: #000000 !important;
    -webkit-text-fill-color: #000000 !important;
    caret-color: #000000 !important;

    border-radius: 12px !important;
    border: 2px solid #90CAF9 !important;

}

textarea::placeholder{
    color:#7A7A7A !important;
}

/* =========================
   METRIC
========================= */

div[data-testid="stMetric"]{

background:rgba(255,255,255,.7);

backdrop-filter:blur(18px);

border-radius:20px;

padding:25px;

border:1px solid rgba(255,255,255,.4);

box-shadow:
0 20px 40px rgba(0,0,0,.08);

}

div[data-testid="stMetricValue"]{

    color:#1565C0 !important;

}

div[data-testid="stMetricLabel"]{

    color:#607D8B !important;

}

/* =========================
   TABS
========================= */

.stTabs [data-baseweb="tab-list"]{

    border-bottom:2px solid #BBDEFB;

}

.stTabs [data-baseweb="tab"]{

    background:#E3F2FD;

    border-radius:10px 10px 0 0;

    color:#183B63 !important;

    font-weight:600;

    padding:10px 22px;

}

.stTabs [aria-selected="true"]{

    color:black !important;

}

/* =========================
   SELECTBOX
========================= */

[data-testid="stSelectbox"] label{
    color:#183B63 !important;
    font-weight:600;
}

[data-baseweb="select"]{
    color:#183B63 !important;
}

[data-baseweb="select"] > div{
    background:#ffffff !important;
    border:2px solid #90CAF9 !important;
    border-radius:10px !important;
    color:#183B63 !important;
}

[data-baseweb="select"] span{
    color:#183B63 !important;
}

[data-baseweb="select"] svg{
    color:#1976D2 !important;
}

[data-baseweb="popover"]{
    background:#ffffff !important;
}

[data-baseweb="menu"]{
    background:#ffffff !important;
}

[data-baseweb="menu"] div{
    color:#183B63 !important;
}

[data-baseweb="menu"] div:hover{
    background:#E3F2FD !important;
}

/* =========================
   FILE UPLOADER
========================= */

[data-testid="stFileUploaderDropzone"]{
    background:#ffffff !important;
    border:2px dashed #64B5F6 !important;
}

/* ==========================
   EXPANDER
========================== */

details{
    background:#ffffff !important;
    border:1px solid #D6E9FF;
    border-radius:12px;
}

summary{
    color:#183B63 !important;
    font-weight:600;
}

summary:hover{
    background:#F5F9FF;
}

/* =========================
   DATAFRAME
========================= */

[data-testid="stDataFrame"]{

border-radius:20px;

overflow:hidden;

border:1px solid #E0EAF4;

box-shadow:
0 10px 30px rgba(0,0,0,.08);

}

/* =========================
   INFO SUCCESS ERROR
========================= */

.stAlert{

    border-radius:12px;

}

/* =========================
   CAPTION
========================= */

[data-testid="stCaptionContainer"]{

    color:#0e1117 !important;

}

/* =========================
   LABEL
========================= */

label{

    color:#183B63 !important;

    font-weight:600;

}

/* =========================
   FOOTER
========================= */

.footer{

    margin-top:60px;

    text-align:center;

    color:#607D8B;

    border-top:1px solid #BBDEFB;

    padding:25px;

    font-size:15px;

}

/* Success */

.stSuccess{
    background:#E8F5E9 !important;
}

/* Warning */

.stWarning{
    background:#FFF8E1 !important;
}

/* Error */

.stError{
    background:#FFEBEE !important;
}

/* Custom Warning Merah */

.custom-warning{
    background:#E53935 !important;
    color:#FFFFFF !important;
    padding:14px 16px !important;
    border-radius:12px !important;
    font-size:15px !important;
    font-weight:500 !important;
    margin:10px 0 !important;
}

.custom-warning *{
    color:#FFFFFF !important;
}

</style>
""", unsafe_allow_html=True)

# ==========================================
# 2. LOAD MODEL & TOKENIZER
# ==========================================
MODEL_PATH = "SonnnJ/indobert_optimal"
DEFAULT_LABEL_MAP = {0: "Negatif", 1: "Netral", 2: "Positif"}

@st.cache_resource
def load_model_and_tokenizer(model_path):
    try:
        # Mengunduh langsung dari Hugging Face Hub secara otomatis
        tokenizer = AutoTokenizer.from_pretrained(model_path)
        model = AutoModelForSequenceClassification.from_pretrained(model_path)
        model.eval()

        raw_id2label = getattr(model.config, "id2label", None)
        if raw_id2label:
            label_map = {int(k): v.capitalize() for k, v in raw_id2label.items()}
        else:
            label_map = DEFAULT_LABEL_MAP

        return tokenizer, model, label_map
    except Exception as e:
        st.error(f"⚠️ Gagal memuat model dari Hugging Face: {e}")
        st.stop()

tokenizer, model, LABEL_MAP = load_model_and_tokenizer(MODEL_PATH)

def clean_text_input(text: str) -> str:
    """Membersihkan raw text (mis. dari Twitter/X) dengan langkah yang PERSIS SAMA
    dengan fungsi clean_text_for_indobert() yang dipakai untuk membuat kolom
    'clean_text' pada data training (lihat notebook, bagian persiapan data).
    Fungsi ini HARUS tetap sinkron dengan versi training -- jangan menambah/mengubah
    langkah cleaning di sini tanpa mengubah juga di notebook & melatih ulang model."""
    if not isinstance(text, str):
        return ""

    text = text.lower()
    text = re.sub(r'https?://\S+|www\.\S+', '', text)      # URL
    text = re.sub(r'@\w+', '', text)                        # mention
    text = re.sub(r'#(\w+)', r'\1', text)                   # hashtag -> ambil katanya, buang simbol #
    text = re.sub(r'[\r\n\t]+', ' ', text)                  # newline & tab
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)             # simbol/emoji dibuang, ANGKA DIPERTAHANKAN
    text = re.sub(r'\s+', ' ', text).strip()                # rapikan spasi
    return text


def predict_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding="max_length", max_length=128)
    with torch.no_grad():
        outputs = model(**inputs)
        probs = torch.softmax(outputs.logits, dim=-1)
        pred_label = torch.argmax(probs, dim=-1).item()

    confidence = probs[0][pred_label].item() * 100
    return LABEL_MAP[pred_label], confidence, probs[0].tolist()
# ==========================================
# 3. SIDEBAR NAVIGATION & INFO
# ==========================================
with st.sidebar:
    st.image("https://img.icons8.com/color/96/garlic.png", width=70)
    st.title("INDOBERT")
    st.caption("Analisis Sentimen Bawang Putih Menggunakan Model IndoBERT")
    st.caption("Jason Gilbert Effendi")
    st.divider()

    st.markdown("### ℹ️ Informasi Model")
    st.write("**Arsitektur:** IndoBERT Base-P1")
    st.write("**Domain:** Persepsi Bawang Putih")

    st.markdown("---")
    st.markdown("### 🏷️ Kategori Sentimen")
    st.markdown("🟢 **Positif**")
    st.markdown("🟡 **Netral**")
    st.markdown("🔴 **Negatif**")

    st.divider()
    with st.expander("ℹ️ Tentang Model"):
        st.markdown("""
### Model yang Digunakan

- **Model** : IndoBERT Base-P1
- **Epoch yang digunakan** : 10

### Performa Model

| Metrik | Nilai |
|--------|-------:|
| Validation Loss | **1.5456** |
| Accuracy | **0.8832** |
| F1 Weighted | **0.8795** |
| F1 Macro | **0.7388** |

Model ini merupakan hasil pelatihan **IndoBERT Base-P1** untuk melakukan klasifikasi sentimen masyarakat terhadap pemanfaatan bawang putih. Model mampu mengklasifikasikan teks ke dalam tiga kategori, yaitu **Positif**, **Netral**, dan **Negatif**.
""")

# ==========================================
# 4. HEADER UTAMA
# ==========================================
st.markdown("""
<div class="header-container">

<h1 class="header-title">
Garlic Sentiment Analyzer
</h1>

</div>
""", unsafe_allow_html=True)

# Tabs
tab1, tab2 = st.tabs(["💬 Uji Kalimat Satuan", "📁 Analisis Dataset (CSV)"])

# ==========================================
# TAB 1: UJI TEKS SATUAN
# ==========================================
with tab1:
    
    st.markdown("#### Input Kalimat / Tweet")
    user_input = st.text_area(
        label="Masukkan teks ulasan masyarakat yang ingin dianalisis:",
        placeholder="Contoh: Konsumsi bawang putih mentah tiap pagi efektif banget buat meredakan flu dan kolesterol.",
        height=100,
        label_visibility="collapsed"
    )

    st.caption("🧹 Teks akan otomatis dibersihkan (URL, mention, hashtag, simbol dihapus) sebelum dianalisis.")

    col_btn, _ = st.columns([1, 4])
    with col_btn:
        analyze_btn = st.button("🔍 Analisis Teks", type="primary", use_container_width=True)

    if analyze_btn:
        if user_input.strip() == "":
            st.markdown("""
            <div class="custom-warning">
                Silakan isi teks terlebih dahulu sebelum melakukan analisis.
            </div>
            """, unsafe_allow_html=True)

        else:
            # Cleaning selalu dijalankan otomatis
            text_to_predict = clean_text_input(user_input)

            with st.spinner("Sedang memproses teks..."):
                label, confidence, probs = predict_sentiment(text_to_predict)

            st.divider()

            # Tampilkan hasil teks setelah dibersihkan
            st.markdown("##### 🧼 Teks Setelah Dibersihkan")

            st.info(
                text_to_predict
                if text_to_predict
                else "_(kosong setelah dibersihkan)_"
            )

            # Layout Hasil Prediksi
            c1, c2 = st.columns([1, 1.5])

            with c1:
                st.markdown("##### Hasil Klasifikasi")

                if label == "Positif":
                    st.success(f"### 🟢 {label}")

                elif label == "Negatif":
                    st.error(f"### 🔴 {label}")

                else:
                    st.warning(f"### 🟡 {label}")

                st.metric(
                    "Tingkat Keyakinan (Confidence)",
                    f"{confidence:.2f}%"
                )

            with c2:
                st.markdown("##### Probabilitas Tiap Kelas")

                # Visualisasi Plotly Interaktif
                sorted_labels = [
                    LABEL_MAP[i]
                    for i in range(len(probs))
                ]

                prob_df = pd.DataFrame({
                    "Sentimen": sorted_labels,
                    "Probabilitas (%)": [
                        p * 100 for p in probs
                    ]
                })

                fig = px.bar(
                    prob_df,
                    x="Sentimen",
                    y="Probabilitas (%)",
                    color="Sentimen",
                    color_discrete_map={
                        "Positif": "#2E7D32",
                        "Netral": "#FBC02D",
                        "Negatif": "#C62828"
                    },
                    text_auto='.1f'
                )

                fig.update_layout(
                    height=240,
                    showlegend=False,
                    plot_bgcolor="rgba(0,0,0,0)",
                    paper_bgcolor="rgba(0,0,0,0)",
                    font=dict(size=15)
                )

                st.plotly_chart(
                    fig,
                    use_container_width=True
                )

# ==========================================
# TAB 2: UPLOAD FILE CSV
# ==========================================
with tab2:
    st.markdown("#### Upload Dataset CSV")
    uploaded_file = st.file_uploader("Unggah file CSV berisi data tweet/ulasan", type=["csv"])

    if uploaded_file is not None:
        try:
            df_upload = pd.read_csv(uploaded_file)

            with st.expander("📋 Pratinjau Dataset", expanded=False):
                st.dataframe(df_upload.head(5), use_container_width=True)

            default_index = 0
            if "cleaned_full_text" in df_upload.columns:
                default_index = list(df_upload.columns).index("cleaned_full_text")

            text_column = st.selectbox(
                "Pilih Kolom Teks yang Akan Dianalisis:",
                options=df_upload.columns,
                index=default_index
            )

            if st.button("⚡ Jalankan Analisis Data", type="primary"):
                with st.status("⏳ Memproses seluruh baris data...", expanded=False):
                    results_label = []
                    results_conf = []
                    cleaned_texts = []

                    for text in df_upload[text_column]:
                        raw_text = str(text).strip() if pd.notna(text) else ""
                        clean_text = clean_text_input(raw_text)
                        cleaned_texts.append(clean_text)

                        if clean_text == "" or clean_text.lower() == "nan":
                            results_label.append("Netral")
                            results_conf.append(0.0)
                        else:
                            lbl, conf, _ = predict_sentiment(clean_text)
                            results_label.append(lbl)
                            results_conf.append(round(conf, 2))

                    df_upload['Teks_Bersih'] = cleaned_texts
                    df_upload['Sentimen_Prediksi'] = results_label
                    df_upload['Confidence (%)'] = results_conf

                st.success("🎉 Analisis massal berhasil diselesaikan!")

                # Ringkasan Metrik
                st.markdown("### 📊 Ringkasan Statistik")
                total_data = len(df_upload)
                pos_count = (df_upload['Sentimen_Prediksi'] == "Positif").sum()
                neg_count = (df_upload['Sentimen_Prediksi'] == "Negatif").sum()
                net_count = (df_upload['Sentimen_Prediksi'] == "Netral").sum()

                m1, m2, m3, m4 = st.columns(4)
                m1.metric("Total Data", f"{total_data:,}")
                m2.metric("🟢 Positif", f"{pos_count}", f"{pos_count/total_data*100:.1f}%")
                m3.metric("🔴 Negatif", f"{neg_count}", f"{neg_count/total_data*100:.1f}%")
                m4.metric("🟡 Netral", f"{net_count}", f"{net_count/total_data*100:.1f}%")

                st.divider()

                # Visualisasi
                col_chart1, col_chart2 = st.columns(2)

                with col_chart1:
                    st.markdown("##### Distribusi Frekuensi Sentimen")
                    counts_df = df_upload['Sentimen_Prediksi'].value_counts().reset_index()
                    counts_df.columns = ['Sentimen', 'Jumlah']
                    fig_bar = px.bar(
                        counts_df, x='Sentimen', y='Jumlah', color='Sentimen',
                        color_discrete_map={"Positif": "#2e7d32", "Netral": "#fbc02d", "Negatif": "#c62828"}
                    )
                    fig_bar.update_layout(showlegend=False, height=300)
                    st.plotly_chart(fig_bar, use_container_width=True)

                with col_chart2:
                    st.markdown("##### Persentase Sentimen")
                    fig_pie = px.pie(
                        counts_df, names='Sentimen', values='Jumlah', hole=0.4,
                        color='Sentimen',
                        color_discrete_map={"Positif": "#2e7d32", "Netral": "#fbc02d", "Negatif": "#c62828"}
                    )
                    fig_pie.update_layout(height=300)
                    st.plotly_chart(fig_pie, use_container_width=True)

                st.markdown("##### 🔍  Hasil Prediksi Semua data")
                st.dataframe(df_upload, use_container_width=True)

                # Download Button
                csv_download = df_upload.to_csv(index=False).encode('utf-8')
                st.download_button(
                    label="📥 Download Hasil Sentimen (CSV)",
                    data=csv_download,
                    file_name="hasil_analisis_sentimen_bawang_putih.csv",
                    mime="text/csv",
                    type="primary"
                )

        except Exception as e:
            st.error(f"Gagal memproses file CSV: {e}")

# ==========================================
# FOOTER
# ==========================================
st.markdown("<div class='footer'>Pengembangan Klasifikasi Sentimen IndoBERT — Tugas Akhir Skripsi © 2026</div>", unsafe_allow_html=True)
